FROM {{ image_name }}:{{ php_version }}-cli

ENV DEBIAN_FRONTEND noninteractive
ENV TERM            xterm-color

RUN \
    apt-get update              && \
    apt-get install -y             \
        apt-transport-https        \
        dirmngr                    \
        gnupg                      \
        software-properties-common \
        supervisor                 \
        unzip                      \
        --no-install-recommends && \
    {% if extensions is not empty %}
        pecl update-channels && \
        {% for name, data in extensions %}
            pecl install {{ name }}{% if data.version is not empty %}-{{ data.version }}{% endif %} && \
        {% endfor %}
        {% for name, data in extensions %}
            {% if data.enabled %}
                docker-php-ext-enable {{ name }} && \
            {% endif %}
        {% endfor %}
    {% endif %}
    pecl install swoole-{{ swoole_version }} && \
    docker-php-ext-enable swoole             && \
    curl                      \
        -sfL                  \
        --connect-timeout 5   \
        --max-time         15 \
        --retry            5  \
        --retry-delay      2  \
        --retry-max-time   60 \
        http://getcomposer.org/installer | php -- --install-dir="/usr/bin" --filename=composer && \
    chmod +x "/usr/bin/composer"                                                               && \
    composer self-update {{ composer.version }}                                                && \
    mkdir -p /var/log/supervisor && \
    rm -r /var/lib/apt/lists/*

COPY ./rootfilesystem/ /

ENTRYPOINT ["/entrypoint.sh"]
CMD []

WORKDIR "/var/www/"
