FROM php:{{ php_version }}-cli-alpine{{ alpine_version }}

RUN \
    set -ex && \
    curl -sfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
    chmod +x /usr/bin/composer                                                                     && \
    composer self-update --clean-backups {{ composer.version }}                                    && \
    apk update && \
    apk add --no-cache libstdc++ && \
    apk add --no-cache --virtual .build-deps $PHPIZE_DEPS {% if option_curl == true  %}curl-dev {% endif %}openssl-dev pcre-dev pcre2-dev zlib-dev && \
    docker-php-ext-install pdo_mysql && \
{%~ if php_extensions is not empty %}
    pecl channel-update pecl.php.net && \
    {%~ for name, data in php_extensions %}
        {%~ if data.configureoptions is empty %}
    pecl install {{ name }}{% if data.version is not empty %}-{{ data.version }}{% endif %} && \
        {%~ else %}
    pecl install --configureoptions '{{ data.configureoptions }}' {{ name }}{% if data.version is not empty %}-{{ data.version }}{% endif %} && \
        {%~ endif %}
    {%~ endfor %}
    {%~ for name, data in php_extensions %}
        {%~ if data.enabled %}
    docker-php-ext-enable {{ name }} && \
        {%~ endif %}
    {%~ endfor %}
{%~ endif %}
    docker-php-ext-install sockets && \
    docker-php-source extract && \
    mkdir /usr/src/php/ext/swoole && \
    curl -sfL https://github.com/swoole/swoole-src/archive/{% if swoole_version == "latest" %}master{% else %}v{{ swoole_version }}{% endif %}.tar.gz -o swoole.tar.gz && \
    tar xfz swoole.tar.gz --strip-components=1 -C /usr/src/php/ext/swoole && \
    docker-php-ext-configure swoole \
        --enable-http2   \
        --enable-mysqlnd \
        --enable-openssl \
        --enable-sockets {% if option_curl == true  %}--enable-swoole-curl {% endif %}{% if option_json == true  %}--enable-swoole-json {% endif %}&& \
    docker-php-ext-install -j$(nproc) swoole && \
    rm -f swoole.tar.gz $HOME/.composer/*-old.phar && \
    docker-php-source delete && \
    apk del .build-deps

WORKDIR "/var/www/"
