FROM {{ image_name }}:{{ php_version }}-cli

ENV DEBIAN_FRONTEND noninteractive
ENV TERM            xterm-color

ARG DEV_MODE
ENV DEV_MODE $DEV_MODE

COPY ./rootfilesystem/ /

RUN \
    curl                      \
        -sfL                  \
        --connect-timeout 5   \
        --max-time         15 \
        --retry            5  \
        --retry-delay      2  \
        --retry-max-time   60 \
        http://getcomposer.org/installer | php -- --install-dir="/usr/bin" --filename=composer && \
    chmod +x "/usr/bin/composer"                                                               && \
    composer self-update {{ composer.version }}                                                                 && \
    apt-get update              && \
    apt-get install -y             \
        cmake                      \
{%~ if inotify == true %}
        inotify-tools              \
{%~ endif %}
        libargon2-0-dev libcurl4-gnutls-dev libedit-dev libncurses5-dev libxml2-dev \
        libpq-dev                  \
        libssl-dev                 \
        supervisor                 \
        unzip                      \
        zlib1g-dev                 \
        --no-install-recommends && \
{%~ if php_extensions is not empty %}
    pecl update-channels && \
    {%~ for name, data in php_extensions %}
    pecl install {{ name }}{% if data.version is not empty %}-{{ data.version }}{% endif %} && \
    {%~ endfor %}
    {%~ for name, data in php_extensions %}
        {%~ if data.enabled %}
    docker-php-ext-enable {{ name }} && \
        {%~ endif %}
    {%~ endfor %}
{%~ endif %}
    SWOOLE_VERSION={{ swoole_version }} \
{%~ for name, data in swoole_extensions %}
    {{ name|upper }}_VERSION={% if data.version is not empty %}{{ data.version }}{%  else %}master{% endif %} \
{%~ endfor %}
        install-swoole.sh && \
{%~ for name, data in swoole_extensions %}
    {%~ if data.enabled %}
    docker-php-ext-enable swoole_{{ name }} && \
    {%~ endif %}
{%~ endfor %}
    mkdir -p /var/log/supervisor && \
    rm -r /var/lib/apt/lists/*

ENTRYPOINT ["/entrypoint.sh"]
CMD []

WORKDIR "/var/www/"
