#!/bin/bash
# @see https://github.com/docker/hub-feedback/issues/1261#issuecomment-441126749 Support automated ARM builds
# @see https://hub.docker.com/r/multiarch/qemu-user-static/

# Register qemu-*-static for all supported processors except the
# current one, but also remove all registered binfmt_misc before
docker run --rm --privileged multiarch/qemu-user-static:register --reset
ls -la rootfilesystem/usr/bin/
ls -la rootfilesystem/usr/local/bin/
