#!/bin/bash

set -eux

if [[ "-dev" == ${DOCKER_TAG:(-4)} ]] ; then
    DEV_MODE=true
else
    DEV_MODE=false
fi

docker build --build-arg DEV_MODE=${DEV_MODE} -t "${IMAGE_NAME}" -f ./Dockerfile ../../../../
