[supervisord]
user = root

[program:swoole]
command = php /var/www/server.php
user = root
autostart = true
autorestart = true
stdout_logfile=/proc/self/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/self/fd/1
stderr_logfile_maxbytes=0
stopasgroup=true
; Less than Docker's default stop timeout (10 seconds), so that Supervisor can stop the server and exit before Docker
; kills the container.
stopwaitsecs=8
